# Setup
title:               Semantic Parsing
tagline:             'a living literature review'
description:         'Research on Modeling and Data resources for Semantic Parsing.'
url:                 https://semantic-parsing.github.io
baseurl:             ''

collections:
  publications:
    output: true
    permalink: /:collection/:path/

plugins_dir:
  - jekyll-sitemap
  - jekyll-seo-tag

sass:
    style: compressed
